<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Authors>Bryan D. Wilhite</Authors>
    <Company>Songhay System</Company>
    <Description>This is a simple demonstration of the Songhay System Shell Activities architecture.</Description>
    <Copyright>(c) 2024 Bryan D. Wilhite</Copyright>
    <RepositoryUrl>https://github.com/BryanWilhite/Songhay.HelloWorlds.Activities</RepositoryUrl>
    <AssemblyVersion>2024.8.08</AssemblyVersion>
    <Deterministic>True</Deterministic>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Songhay.HelloWorlds</RootNamespace>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>1701;1702;1705;CS7035</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SonghayCore" Version="6.1.4" />
  </ItemGroup>

</Project>
